apiVersion: "autoscaling.openshift.io/v1"
kind: "ClusterAutoscaler"
metadata:
  name: "default"
spec:
  podPriorityThreshold: 0 
  resourceLimits:
    maxNodesTotal: 24
    cores:
      min: 4 
      max: 256 
    memory:
      min: 4 
      max: 512
  scaleDown: 
    enabled: true 
    delayAfterAdd: 10m 
    delayAfterDelete: 5m 
    delayAfterFailure: 30s 
    unneededTime: 5m

